### ISSUE TITLE
Can't build on Windows 7 64bits

### ISSUE THREAD

**Issue by corentingurtner** [xdissent/node-pcm-utils#4]
I got this errors, building on Windows 7 64 bits with node 0.10.17

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  mixer.cc
  unzipper.cc
  zipper.cc
  formatter.cc
c:\github\node-pcm-utils\unzipper.h(70): warning C4267: '=' : conversion de 'size_t' en 'int', perte possible de données (..\binding.cc) [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
..\mixer.cc(112): error C2466: impossible d'allouer un tableau de taille constante 0 [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
..\mixer.cc(112): error C2440: 'initialisation' : impossible de convertir de 'int' en 'v8::Local<v8::Value>' [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
          Aucun constructeur n'a pu prendre le type de source, ou la résolution de la surcharge du constructeur était ambiguë
..\formatter.cc(69): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
..\zipper.cc(110): error C2466: impossible d'allouer un tableau de taille constante 0 [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
..\zipper.cc(110): error C2440: 'initialisation' : impossible de convertir de 'int' en 'v8::Local<v8::Value>' [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
          Aucun constructeur n'a pu prendre le type de source, ou la résolution de la surcharge du constructeur était ambiguë
c:\github\node-pcm-utils\unzipper.h(70): warning C4267: '=' : conversion de 'size_t' en 'int', perte possible de données (..\unzipper.cc) [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
C:\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\binding.cc) [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
C:\.node-gyp\0.10.35\deps\v8\include\v8.h(218): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\formatter.cc) [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
C:\.node-gyp\0.10.35\deps\v8\include\v8.h(218): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\unzipper.cc) [c:\GitHub\node-pcm-utils\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\GitHub\node-pcm-utils
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm info pcm-utils@0.0.2 Failed to exec install script
npm ERR! pcm-utils@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcm-utils@0.0.2 install script.
npm ERR! This is most likely a problem with the pcm-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pcm-utils
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-d"
npm ERR! cwd c:\GitHub\node-pcm-utils
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\GitHub\node-pcm-utils\npm-debug.log
npm ERR! not ok code 0
```

I will try to fix it when I have time.

**Comment by xdissent** [comment]
Ah, the old `int` instead of `size_t` bug. Gets me every time! ;-)
Sorry about that, I'll be working on this project this weekend or shortly thereafter and will make sure to straighten that out.

**Comment by dy** [comment]
+1. The same error.
